# -*- mode: ruby -*-
# vi: set ft=ruby :

#/**
#
#* Copyright 2014, Hortonworks Inc.  All rights reserved.
#
#* Licensed under the Apache License, Version 2.0 (the "License");
#* you may not use this file except in compliance with the License.
#* You may obtain a copy of the License at
#
#* http://www.apache.org/licenses/LICENSE-2.0
#
#* Unless required by applicable law or agreed to in writing, software
#* distributed under the License is distributed on an "AS IS" BASIS,
#* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#* See the License for the specific language governing permissions and
#* limitations under the License.
#
##########################################################
# to bring machine up do $ vagrant up <machine name>
# 
# Available <Machine name>s:
#  - hdp: gsinstaller playground
##########################################################

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # All Vagrant configuration is done here. The most common configuration
  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "centos6.4"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.

  # CentOS 6.4 x86_64 Minimal (VirtualBox Guest Additions 4.2.12, Chef 11.4.4, Puppet 3.1.1)
  # config.vm.box_url = "http://developer.nrel.gov/downloads/vagrant-boxes/CentOS-6.4-x86_64-v20130427.box"
  config.vm.box_url = "https://dl.dropbox.com/u/5721940/vagrant-boxes/vagrant-centos-6.4-x86_64-vmware_fusion.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 2048]
  end
  config.vm.provider "vmware_fusion" do |v|
  end

  $ant_script = <<END_ANT
  mkdir /home/vagrant/tools
  wget -P /home/vagrant/tools http://apache.mirrors.pair.com//ant/binaries/apache-ant-1.9.3-bin.tar.gz
  tar zx -C /home/vagrant/tools -f /home/vagrant/tools/apache-ant-1.9.3-bin.tar.gz
  sed 's@PATH=.*@&:/home/vagrant/tools/apache-ant-1.9.3/bin@' /home/vagrant/.bash_profile > /tmp/tmp_profile
  mv /tmp/tmp_profile /home/vagrant/.bash_profile
END_ANT

  config.vm.provision :shell, :inline => "yum install -y screen"
  config.vm.provision :shell, :inline => "yum install -y java-1.7.0-openjdk-devel"
  config.vm.provision :shell, :inline => "yum install -y git"
  config.vm.provision :shell, :inline => "yum install -y wget"
  config.vm.provision :shell, :inline => "rpm -i /vagrant/maven-3.0.4-2.2.noarch.rpm"
  config.vm.provision :shell, :inline => "rpm -i /vagrant/protobuf-2.5.0-16.1.x86_64.rpm"
  config.vm.provision :shell, :inline => "rpm -i /vagrant/protobuf-compiler-2.5.0-16.1.x86_64.rpm"
  config.vm.provision :shell, :inline => $ant_script
end
